server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/webservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: datnguyen101004@gmail.com
    password: hozg yohs htni gswl
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

gemini:
  api:
    key: AIzaSyCuH35gLRCsoPLfq6cGTa2pcGR2eORf3kM


